{"name": "Проверка успешной аутентификации курьера при вводе валидных данных", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 200)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_courier_login.TestCourierLogin object at 0x0000027DF36A9810>\n\n    @allure.title('Проверка успешной аутентификации курьера при вводе валидных данных')\n    @allure.description('Happy path. Проверяются код и тело ответа.')\n    def test_courier_login_success(self):\n        response = requests.post(Urls.URL_courier_login, data=Data.valid_courier_data)\n>       assert response.status_code == 200 and 'id' in response.text\nE       assert (404 == 200)\nE        +  where 404 = <Response [404]>.status_code\n\ntest_courier_login.py:15: AssertionError"}, "description": "Happy path. Проверяются код и тело ответа.", "start": 1754316236931, "stop": 1754316237055, "uuid": "15cff616-dda5-4b30-823c-4457eebac15d", "historyId": "c324956a340af00dac555e0fdb55823f", "testCaseId": "c324956a340af00dac555e0fdb55823f", "fullName": "test_courier_login.TestCourierLogin#test_courier_login_success", "labels": [{"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Vova"}, {"name": "thread", "value": "23024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier_login"}]}